import type { Template } from "@/lib/domain/types";

export const builtInTemplates: Template[] = [
  {
    id: "tpl_neon_pulse",
    name: "Neon Pulse",
    category: "music",
    particleConfig: { preset: "neon", density: 0.6, speed: 0.7 },
    equalizerConfig: {
      x: 0.5,
      y: 0.82,
      width: 0.74,
      height: 0.2,
      color: "#00E5FF",
      visualizerType: "symmetricBars",
    },
    posterConfig: {
      cornerRadius: 24,
      blurStrength: 22,
      backgroundDimStrength: 0.5,
    },
    defaultPalette: ["#00E5FF", "#12203D", "#F8FAFF"],
    isBuiltIn: true,
  },
  {
    id: "tpl_amber_wave",
    name: "Amber Wave",
    category: "warm",
    particleConfig: { preset: "dust", density: 0.5, speed: 0.45 },
    equalizerConfig: {
      x: 0.5,
      y: 0.8,
      width: 0.7,
      height: 0.18,
      color: "#FFB347",
      visualizerType: "line",
    },
    posterConfig: {
      cornerRadius: 16,
      blurStrength: 18,
      backgroundDimStrength: 0.44,
    },
    defaultPalette: ["#FFB347", "#34120C", "#FFF8E8"],
    isBuiltIn: true,
  },
  {
    id: "tpl_cobalt_grid",
    name: "Cobalt Grid",
    category: "tech",
    particleConfig: { preset: "geometric", density: 0.35, speed: 0.3 },
    equalizerConfig: {
      x: 0.5,
      y: 0.78,
      width: 0.62,
      height: 0.17,
      color: "#5AA9FF",
      visualizerType: "dots",
    },
    posterConfig: {
      cornerRadius: 8,
      blurStrength: 14,
      backgroundDimStrength: 0.42,
    },
    defaultPalette: ["#5AA9FF", "#0A1630", "#D9EBFF"],
    isBuiltIn: true,
  },
  {
    id: "tpl_sunset_drive",
    name: "Sunset Drive",
    category: "retro",
    particleConfig: { preset: "fire", density: 0.65, speed: 0.55 },
    equalizerConfig: {
      x: 0.5,
      y: 0.83,
      width: 0.78,
      height: 0.2,
      color: "#FF6B6B",
      visualizerType: "bars",
    },
    posterConfig: {
      cornerRadius: 28,
      blurStrength: 26,
      backgroundDimStrength: 0.56,
    },
    defaultPalette: ["#FF6B6B", "#3A123E", "#FFE7CF"],
    isBuiltIn: true,
  },
  {
    id: "tpl_stardust_lowfi",
    name: "Stardust Lo-Fi",
    category: "lofi",
    particleConfig: { preset: "stardust", density: 0.42, speed: 0.22 },
    equalizerConfig: {
      x: 0.5,
      y: 0.81,
      width: 0.68,
      height: 0.16,
      color: "#B9C6FF",
      visualizerType: "line",
    },
    posterConfig: {
      cornerRadius: 20,
      blurStrength: 20,
      backgroundDimStrength: 0.48,
    },
    defaultPalette: ["#B9C6FF", "#13142A", "#EFEFFF"],
    isBuiltIn: true,
  },
];
